version: "3"
services:
  site:
    image: jekyll/jekyll:latest
    command: jekyll serve
    working_dir: /srv/jekyll
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
