services:
  - type: web
    name: tr.com
    runtime: static
    buildCommand: npm i -g pnpm && pnpm i && pnpm run build
    staticPublishPath: ./.vitepress/dist
    pullRequestPreviewsEnabled: true
    domains:
      - taskratchet.com
      - www.taskratchet.com
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
