services:
  - type: web
    name: TaskRatchet.com
    runtime: static
    buildCommand: npm i -g pnpm && pnpm i && pnpm run build
    staticPublishPath: ./site/.vitepress/dist
    pullRequestPreviewEnabled: true
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true